import * as admin from 'firebase-admin';

/**
 * The data that arduino devices generate
 */
export interface Data {
  id: string;
  timestamp: admin.firestore.Timestamp;
  value: number;
}

/**
 * The report generated by the generator function
 */
export interface Report {
  timestamp: admin.firestore.Timestamp;
}
